### ISSUE TITLE
Right-click menus not coloured

### ISSUE THREAD

**Issue by pseudohero** [coekuss/quietfox#10]
Hi there.

Thanks for this awesome CSS.

I am using it on Firefox 76.0.1. I have my theme set to change automatically depending on the system theme (light or dark). Regardless of which theme I am on however, any right-click menus are always transparent:

![Untitled](https://user-images.githubusercontent.com/57340106/81782845-c6425100-953d-11ea-8ecc-b1f6e662f5a5.png)

Am I supposed to be using a non-native theme, i.e. am I meant to be using a "theme" in the form of userChrome and add your CSS to it, or should native themes from the Firefox addons page work?

Thanks heaps for your help!

**Comment by coekuss** [comment]
transparent menus have been fixed in the [latest update](https://github.com/coekuss/quietfox/releases)

**Comment by pseudohero** [comment]
Lovely, thank you!
