### ISSUE TITLE
Buggy pixels next to tabs on top.

### ISSUE THREAD

**Issue by sevenfivesixnine** [coekuss/quietfox#2]
I'm currently running Firefox Nightly 72.0a1 and I've noticed buggy pixels at the top bar with tabs pretty much instantly. When I open new tab on top pixels from the last one bug into the new one. This happens with each new tab opened. I know you've just tested version 70 of stable release but I just wanted to let you know.

**Comment by icejr** [comment]
This issue is present in latest Firefox 71.0

**Comment by coekuss** [comment]
Just updated my Firefox to 71.0 and now the issue is visible on my end, I'll address it soon and release a Quietfox 71. Hopefully then it will work with current Nightly releases too
