### ISSUE TITLE
New store for FirefoxCSS themes

### ISSUE THREAD

**Issue by Neikon** [coekuss/quietfox#20]
Hi, I don't know how to contact you so I'm using this.

We are creating a website where to collect firefox themes. we have included yours by linking to this github. But we don't have a good preview image of your theme. It would be nice if you could provide it.

I invite you to add/change/remove any information we have added to our website. I hope you like the initiative and that in the future you will send us more themes.

here are the links:
web: https://firefoxcss-store.github.io/
repo: https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io

Regards :)

**Comment by coekuss** [comment]
Hey thanks for featuring me in your collection, it's pretty cool. I just made this image that looks like it'll fit your site:

![quietfox](https://user-images.githubusercontent.com/45906331/105771685-c9d40780-5f15-11eb-9d12-c319d18d372f.jpg)

I hope it's a good image. The info in the site looks good
