### ISSUE TITLE
[Request] Context Menu - (Optional) Navigation buttons?

### ISSUE THREAD

**Issue by dst27** [coekuss/quietfox#22]
**Background:** The default Firefox context menu includes buttons to reload and navigate backwards. Major browsers including the new Edge and Brave also include these buttons in the context menu. These buttons can therefore be useful to have for the sake of consistency and for those who're used to them in the context menu which I assume includes many Firefox users too.

![image](https://user-images.githubusercontent.com/72784348/106465519-0ed0de80-64c0-11eb-9f62-5d5eca9f10bf.png)

**Proposed Solution:** I would like it if quietfox could also have them even as an optional switch so they can be enabled by those who want them if not as a default.

**Comment by coekuss** [comment]
Good point, a quick fix is you can remove lines [694 and 695](https://github.com/coekuss/quietfox/blob/147ad4a5b01c212b5fc719e9396d6f042ae51808/chrome/userChrome.css#L694) to bring back navigation buttons in the menu.
Then add this to make the navigation buttons' background color match the rest of the menu:
```
#context-navigation {
    background-color: var(--toolbar-bgcolor) !important;
}
```
Should look like this:
![image](https://user-images.githubusercontent.com/45906331/106516740-81809080-64a5-11eb-9526-40e484f00bc5.png)

I'll look into adding this as a customization switch in the future.
