### ISSUE TITLE
Address bar is distorted in Firefox 76

### ISSUE THREAD

**Issue by ducky710** [coekuss/quietfox#5]
Due to the latest changes to the address bar in 76, it appears very wonky when you click into it.

**Comment by coekuss** [comment]
just released the fix for Firefox 75. Firefox 76 is still Beta and I'm only planning to maintain Quietfox for Stable Firefox. Hope this helps though

**Comment by 1Gokul** [comment]
Nice! I had reverted to the original dark theme for some time to wait for this update. 
Looks like they're making this new bar the norm as they've removed all the quick fixes people are using to get the original bar back in the Nightly version.

**Comment by ducky710** [comment]
Sweet thanks this did in fact fix it :)

**Comment by Excigma** [comment]
The right click menu is also transparent now (Firefox 76)

![image](https://user-images.githubusercontent.com/30280397/79338168-ec92c200-7f7a-11ea-80ab-4a8b38fd0f16.png)

Just to let you know too
